import { mkdir, readFile, writeFile } from "node:fs/promises"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const itemsPath = join(__dirname, "../src/data/items.ts")
const outputPath = join(__dirname, "../src/data/generated/boostItems.ts")

// The core store only needs boost metadata for vial lookups, not the full item
// dataset. Emits the tokenId/boostType expressions verbatim (resolved by the
// consuming TS build) to avoid having to evaluate EstforConstants here.
async function generateBoostItems() {
    const contents = await readFile(itemsPath, "utf8")
    const entries = []
    const seenTokenIds = new Set()

    const segments = contents.split(/\n  \{/).slice(1)
    if (segments.length === 0) {
        throw new Error(`No items found in ${itemsPath}`)
    }

    for (const segment of segments) {
        const tokenId = segment.match(/^\s*tokenId:\s*(.+?),\s*$/m)?.[1]
        const boostType = segment.match(/^\s*boostType:\s*([\w.]+),\s*$/m)?.[1]
        const boostValue = segment.match(
            /^\s*boostValue:\s*(-?\d+),\s*$/m
        )?.[1]
        const boostDuration = segment.match(
            /^\s*boostDuration:\s*(-?\d+),\s*$/m
        )?.[1]

        if (!tokenId || !boostType || !boostValue || !boostDuration) {
            throw new Error(`Could not parse item segment: ${segment.slice(0, 120)}`)
        }

        if (boostType === "BoostType.NONE") {
            continue
        }
        if (seenTokenIds.has(tokenId)) {
            throw new Error(`Duplicate boosted tokenId: ${tokenId}`)
        }
        seenTokenIds.add(tokenId)

        entries.push({ tokenId, boostType, boostValue, boostDuration })
    }

    if (
        !entries.some((x) => x.tokenId === "EstforConstants.LUCK_OF_THE_DRAW")
    ) {
        throw new Error("LUCK_OF_THE_DRAW is missing from the boost items")
    }

    entries.sort(
        (a, b) =>
            Number(a.tokenId.match(/\d+/)?.[0] ?? 0) -
            Number(b.tokenId.match(/\d+/)?.[0] ?? 0)
    )

    await mkdir(dirname(outputPath), { recursive: true })
    await writeFile(
        outputPath,
        [
            "// Generated by scripts/generateBoostItems.mjs - do not edit.",
            'import { EstforConstants } from "@paintswap/estfor-definitions"',
            'import { BoostType } from "@paintswap/estfor-definitions/types"',
            "",
            "export interface BoostItem {",
            "    boostType: BoostType",
            "    boostValue: number",
            "    boostDuration: number",
            "}",
            "",
            "export const boostItems: Record<number, BoostItem> = {",
            ...entries.map(
                (x) =>
                    `    [${x.tokenId}]: {\n        boostType: ${x.boostType},\n        boostValue: ${x.boostValue},\n        boostDuration: ${x.boostDuration},\n    },`
            ),
            "}",
            "",
        ].join("\n"),
        "utf8"
    )
}

generateBoostItems().then(() => {
    console.log(`Generated ${outputPath}`)
})
