import { readFile, mkdir, writeFile } from "node:fs/promises"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const itemsPath = join(__dirname, "../src/data/items.ts")
const outputPath = join(__dirname, "../src/data/generated/searchableItemNames.ts")

async function generateItemNames() {
    const contents = await readFile(itemsPath, "utf8")
    const names = []
    const seen = new Set()
    const pattern = /^\s*name:\s*"((?:[^"\\]|\\.)*)",?\s*$/gm

    let match
    while ((match = pattern.exec(contents)) !== null) {
        const name = match[1].replaceAll('\\"', '"').replaceAll("\\\\", "\\")
        if (!seen.has(name)) {
            seen.add(name)
            names.push(name)
        }
    }

    if (names.length === 0) {
        throw new Error(`No item names found in ${itemsPath}`)
    }

    names.sort(new Intl.Collator("en", { sensitivity: "base", numeric: true }).compare)

    await mkdir(dirname(outputPath), { recursive: true })
    await writeFile(
        outputPath,
        [
            "// Generated by scripts/generateItemNames.mjs - do not edit.",
            "export const searchableItemNames = [",
            ...names.map((name) => `    "${name}",`),
            "] as const",
            "",
        ].join("\n"),
        "utf8"
    )
}

generateItemNames().then(() => {
    console.log(`Generated ${outputPath}`)
})
